export enum GAME_MODES {
	"QUICK_GAME" = "QUICK_GAME",
	"CASUAL_GAME" = "CASUAL_GAME",
	"RANKED_GAME" = "RANKED_GAME",
}

export enum ADDITIONAL_GAME_MODES {
	NO_TIMERS = "NO_TIMERS",
	WITH_PORTAL = "WITH_PORTAL",
	WITH_ROULETTE = "WITH_ROULETTE",
}
